# wrangler.toml
name = "it-engineer-game"

account_id = "4445b33ac7b79666bea21e00bcb65c72" # Ваш реальный Account ID
workers_dev = true
compatibility_date = "2024-09-20"

main = "./workers-site/index.js"

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "it-engineer-game-assets" # Название вашего R2 Bucket
preview_bucket_name = "it-engineer-game-assets"